sonar.organization=bushko6
sonar.projectKey=Bushko6_shopping-list-app
sonar.projectName=Shopping List App
sonar.python.version=3.12
sonar.sources=src
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=junit.xml
sonar.coverage.exclusions=tests/,**/__init__.py
