from abc import ABC, abstractmethod
from typing import Optional
from models.shopping_list import ShoppingList
from models.shopping_item import ShoppingItem
from models.category import Category
from models.user import User


class ShoppingListRepository(ABC):
    @abstractmethod
    def add(self, shopping_list: ShoppingList) -> None: ...
    @abstractmethod
    def get_by_id(self, list_id: str) -> Optional[ShoppingList]: ...
    @abstractmethod
    def list_all(self) -> list[ShoppingList]: ...
    @abstractmethod
    def update(self, shopping_list: ShoppingList) -> None: ...
    @abstractmethod
    def delete(self, list_id: str) -> None: ...
    @abstractmethod
    def find_by_owner(self, owner_id: str) -> list[ShoppingList]: ...


class ShoppingItemRepository(ABC):
    @abstractmethod
    def add(self, item: ShoppingItem) -> None: ...
    @abstractmethod
    def get_by_id(self, item_id: str) -> Optional[ShoppingItem]: ...
    @abstractmethod
    def list_all(self) -> list[ShoppingItem]: ...
    @abstractmethod
    def update(self, item: ShoppingItem) -> None: ...
    @abstractmethod
    def delete(self, item_id: str) -> None: ...
    @abstractmethod
    def find_by_list(self, list_id: str) -> list[ShoppingItem]: ...
    @abstractmethod
    def find_unpurchased_by_list(self, list_id: str) -> list[ShoppingItem]: ...


class CategoryRepository(ABC):
    @abstractmethod
    def add(self, category: Category) -> None: ...
    @abstractmethod
    def get_by_id(self, category_id: str) -> Optional[Category]: ...
    @abstractmethod
    def list_all(self) -> list[Category]: ...
    @abstractmethod
    def update(self, category: Category) -> None: ...
    @abstractmethod
    def delete(self, category_id: str) -> None: ...
    @abstractmethod
    def find_by_name(self, name: str) -> Optional[Category]: ...


class UserRepository(ABC):
    @abstractmethod
    def add(self, user: User) -> None: ...
    @abstractmethod
    def get_by_id(self, user_id: str) -> Optional[User]: ...
    @abstractmethod
    def list_all(self) -> list[User]: ...
    @abstractmethod
    def update(self, user: User) -> None: ...
    @abstractmethod
    def delete(self, user_id: str) -> None: ...
    @abstractmethod
    def find_by_email(self, email: str) -> Optional[User]: ...
